version: "3"

services:

  runtime-setup:
    image: brotli4j:default
    build:
      context: .
      dockerfile: Dockerfile17.centos6

  common: &common
    image: brotli4j:default
    depends_on: [ runtime-setup ]
    volumes:
      - ~/.m2:/root/.m2
      - ..:/code
    working_dir: /code

  build:
    <<: *common
    command:
      - /bin/bash
      - -cl
      - |
        JAVA_HOME=/jdk  mvn -B --show-version -ntp --file pom.xml clean package
        # Test with JDK 8
        JAVA_HOME=/jdk8 mvn -B --show-version -ntp --file pom.xml surefire:test

  shell:
    <<: *common
    entrypoint: /bin/bash
