name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  MacOS-Build:
    strategy:
      fail-fast: true
      matrix:
        java_version: [ 8, 11, 17, 21 ]

    name: MacOS-x86_64-Build-JDK${{ matrix.java_version }}
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java_version }}
          architecture: 'x64'

      - name: Build
        run: mvn -B -V -ntp --file pom.xml clean package

      - name: Upload build
        if: ${{ matrix.java_version == 8 }}
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-x86_64-Build-JDK${{ matrix.java_version }}
          path: .

  Linux-Build:
    strategy:
      fail-fast: true
      matrix:
        architecture: [ x86_64, x86 ]
        java_version: [ 8,11,17,21 ]

    name: Linux-${{ matrix.architecture }}-Build-JDK${{ matrix.java_version }}
    runs-on: ubuntu-latest

    if: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java_version }}
          architecture: 'x64'
      - name: Build
        run: mvn -B -V -ntp --file pom.xml clean package
      - name: Upload build
        if: ${{ matrix.java_version == 8 }}
        uses: actions/upload-artifact@v4
        with:
          name: Linux-${{ matrix.architecture }}-Build-JDK${{ matrix.java_version }}
          path: .

  Windows-Build:
    strategy:
      fail-fast: true
      matrix:
        architecture:
          - name: x86_64
            msvc_code: x64
          - name: x86
            msvc_code: x64_x86
          - name: aarch64
            msvc_code: x64_arm64
          - name: armv7
            msvc_code: x64_arm
        java_version: [ 8, 11, 17, 21 ]

    name: Windows-${{ matrix.architecture.name }}-Build-JDK${{ matrix.java_version }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java_version }}
          architecture: 'x64'

      - name: Enable compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture.msvc_code }}

      - name: Build
        run: mvn -B -V -ntp --file pom.xml clean package

      - name: Upload build
        if: ${{ matrix.java_version == 8 }}
        uses: actions/upload-artifact@v4
        with:
          name: Windows-${{ matrix.architecture.name }}-Build-JDK${{ matrix.java_version }}
          path: .